### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pricna**
Noticed this was lacking some relevant introductory information, so this would accomplish that.

### CODE REVIEW

**Comment by SamuelSHernandez** [comment]
Thank you Nate!

**Comment by pricna** [comment]
I don't have permission to merge to main anymore, which is why I sent the request. Though, it seems it is still unmerged @SamuelSHernandez.

**Comment by SamuelSHernandez** [comment]
@pricna I gave you admin permissions and reopened the branch.

**Comment by pricna** [comment]
Still seem to be listed as a member and cannot merge without a review still @SamuelSHernandez.

> @pricna I gave you admin permissions and reopened the branch.

**Pull request merged**
